name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: My first action
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FIRST_NAME: Mona
          LAST_NAME: Octocat

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run JavaScript Script
        run: |
          echo "My secret key is $SECRET_KEY"
          echo "::set-env name=SECRET_KEY::$SECRET_KEY"  # Setting the environment variable for subsequent steps
          node my-script.js